# Generated by Django 4.2.3 on 2023-07-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='beak_shape',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='finch',
            name='common_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='finch',
            name='food',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='finch',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='finch',
            name='scientific_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
