# Generated by Django 4.2.3 on 2023-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_finch_beak_shape_finch_common_name_finch_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
