# Generated by Django 4.2.3 on 2023-07-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_sighting_options_remove_finch_food_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='finches',
        ),
        migrations.AddField(
            model_name='finch',
            name='food',
            field=models.ManyToManyField(blank=True, to='main_app.food'),
        ),
    ]
